import { StyleSheet } from 'react-native';

const Bookstyle = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    container: {
      flex: 1,
      backgroundColor: '#F9FAFB',
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
    },
    centeredContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    loadingText: {
      marginTop: 10,
      fontSize: 16,
      color: '#6B7280',
    },
    errorText: {
        fontSize: 12,
        color: '#EF4444',
        marginTop: 4,
        marginLeft: 4,
    },
    infoText: {
        fontSize: 18,
        textAlign: 'center',
        color: '#1F2937',
        marginBottom: 20
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
      backgroundColor: '#FFFFFF',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    backButton: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: '#F3F4F6',
    },
    headerCenter: {
      flex: 1,
      alignItems: 'center',
    },
    headerRight: {
      width: 40,
    },
    title: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#000',
    },
    formContent: {
      padding: 24,
      paddingBottom: 40,
    },
    monasteryInfo: {
      backgroundColor: '#FFF7ED',
      padding: 20,
      borderRadius: 16,
      marginBottom: 32,
      borderWidth: 1,
      borderColor: '#FED7AA',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    monasteryName: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#1F2937',
      marginBottom: 6,
    },
    monasteryLocation: {
      fontSize: 16,
      color: '#6B7280',
    },
    inputGroup: {
      marginBottom: 24,
    },
    label: {
      fontSize: 16,
      fontWeight: '600',
      color: '#1F2937',
      marginBottom: 8,
    },
    labelHint: {
      fontSize: 14,
      fontWeight: '400',
      color: '#6B7280',
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 2,
      borderColor: '#E5E7EB',
      paddingHorizontal: 16,
      minHeight: 56,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    disabledInputContainer: {
        backgroundColor: '#F9FAFB',
        borderColor: '#D1D5DB',
    },
    icon: {
      marginRight: 12,
    },
    input: {
      flex: 1,
      fontSize: 16,
      color: '#1F2937',
      paddingVertical: 16,
    },
    disabledInput: {
      color: '#9CA3AF',
    },
    dateText: {
      paddingVertical: 16,
    },
    placeholderText: {
      color: '#9CA3AF',
    },
    textAreaIcon: {
      marginRight: 12,
      alignSelf: 'flex-start',
      marginTop: 16,
    },
    textArea: {
      minHeight: 100,
      textAlignVertical: 'top',
      paddingTop: 16,
      paddingBottom: 16,
    },
    counterContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 2,
      borderColor: '#E5E7EB',
      paddingHorizontal: 16,
      minHeight: 56,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    counterIcon: {
      marginRight: 12,
    },
    counter: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    counterButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#FFF7ED',
      borderWidth: 2,
      borderColor: '#DF8020',
      alignItems: 'center',
      justifyContent: 'center',
    },
    counterButtonDisabled: {
      backgroundColor: '#F3F4F6',
      borderColor: '#D1D5DB',
    },
    counterValue: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#1F2937',
      minWidth: 30,
      textAlign: 'center',
    },
    button: {
      backgroundColor: '#DF8020',
      paddingVertical: 18,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 32,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    buttonDisabled: {
      backgroundColor: '#D1D5DB',
      elevation: 0,
      shadowOpacity: 0,
    },
    buttonText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: 'bold',
    },
    // Calendar Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    calendarModal: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 20,
      width: '100%',
      maxWidth: 350,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 10,
    },
    calendarHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 20,
      paddingHorizontal: 10,
    },
    monthNav: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: '#F3F4F6',
    },
    monthYear: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#1F2937',
    },
    weekDays: {
      flexDirection: 'row',
      marginBottom: 10,
    },
    weekDay: {
      flex: 1,
      textAlign: 'center',
      fontSize: 14,
      fontWeight: '600',
      color: '#6B7280',
      paddingVertical: 8,
    },
    calendar: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 20,
    },
    calendarDay: {
      width: '14.28%',
      aspectRatio: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      marginVertical: 2,
    },
    calendarDayInactive: {
      opacity: 0.3,
    },
    calendarDayPast: {
      opacity: 0.3,
    },
    calendarDaySelected: {
      backgroundColor: '#DF8020',
    },
    calendarDayToday: {
      borderWidth: 2,
      borderColor: '#DF8020',
    },
    calendarDayText: {
      fontSize: 16,
      color: '#1F2937',
    },
    calendarDayTextInactive: {
      color: '#9CA3AF',
    },
    calendarDayTextPast: {
      color: '#D1D5DB',
    },
    calendarDayTextSelected: {
      color: '#FFFFFF',
      fontWeight: 'bold',
    },
    calendarDayTextToday: {
      fontWeight: 'bold',
      color: '#DF8020',
    },
    calendarCloseButton: {
      backgroundColor: '#F3F4F6',
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    calendarCloseText: {
      fontSize: 16,
      color: '#6B7280',
      fontWeight: '600',
    },
    // New improved date picker styles
    datePickerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      paddingHorizontal: 16,
      paddingVertical: 12,
      minHeight: 56,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    dateIconContainer: {
      width: 40,
      height: 40,
      backgroundColor: '#F3F4F6',
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    dateDisplayText: {
      flex: 1,
      fontSize: 16,
      color: '#1F2937',
      fontWeight: '500',
    },
    // New improved visitor counter styles
    visitorContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      paddingHorizontal: 16,
      paddingVertical: 12,
      minHeight: 56,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    visitorIconContainer: {
      width: 40,
      height: 40,
      backgroundColor: '#F3F4F6',
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    visitorInfo: {
      flex: 1,
    },
    visitorLabel: {
      fontSize: 16,
      color: '#1F2937',
      fontWeight: '500',
    },
    visitorControls: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    visitorButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: '#10B981',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    visitorButtonDisabled: {
      backgroundColor: '#D1D5DB',
      shadowOpacity: 0,
      elevation: 0,
    },
    visitorCount: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#1F2937',
      marginHorizontal: 16,
      minWidth: 30,
      textAlign: 'center',
    },
  });

export default Bookstyle;