export const mockMonasteries = [
  {
    id: '1',
    name: 'Hemis Monastery',
    location: 'Ladakh, India',
    era: '17th Century',
    description: 'Largest and wealthiest monastery in Ladakh, famous for its annual Hemis Festival',
    history: 'Founded in 1630 by the first incarnation of Stagsang Raspa Nawang Gyatso, under the patronage of King Sengge Namgyal. The monastery belongs to the Drukpa Lineage of the Kagyu school of Tibetan Buddhism.',
    cultural_significance: 'Home to rare Buddhist manuscripts, thangkas, and the largest Thangka in Ladakh unveiled every 12 years during Hemis Festival.',
    images: ['https://images.pexels.com/photos/2050718/pexels-photo-2050718.jpeg'],
    latitude: 34.2676,
    longitude: 77.6663,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Tashilhunpo Monastery',
    location: 'Shigatse, Tibet',
    era: '15th Century',
    description: 'Seat of the Panchen Lama and one of the Big Six monasteries of the Gelug school',
    history: 'Founded in 1447 by Gedun Drupa, the 1st Dalai Lama. It has been the traditional seat of successive Panchen Lamas, the second highest ranking tulku lineage in the Gelug tradition of Tibetan Buddhism.',
    cultural_significance: 'Important center for Tibetan Buddhist learning with a massive statue of Maitreya Buddha and extensive monastic university.',
    images: ['https://images.pexels.com/photos/1770809/pexels-photo-1770809.jpeg'],
    latitude: 29.2675,
    longitude: 88.8780,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Tengboche Monastery',
    location: 'Nepal',
    era: '20th Century',
    description: 'Sacred monastery in the Everest region, destroyed and rebuilt multiple times',
    history: 'Originally built in 1916, destroyed by earthquake in 1934, rebuilt, then destroyed by fire in 1989 and rebuilt again. It is the largest gompa in the Khumbu region of Nepal.',
    cultural_significance: 'Spiritual center for Sherpa community and trekkers, famous for its location with panoramic views of Everest, Lhotse, and Ama Dablam.',
    images: ['https://images.pexels.com/photos/2832382/pexels-photo-2832382.jpeg'],
    latitude: 27.8360,
    longitude: 86.7644,
    created_at: new Date().toISOString(),
  },
];

export const mockReviews = [
  {
    id: '1',
    monastery_id: '1',
    user_id: 'user1',
    rating: 5,
    comment: 'Absolutely breathtaking monastery with rich spiritual atmosphere. The annual festival is a must-see!',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    monastery_id: '1',
    user_id: 'user2',
    rating: 4,
    comment: 'Beautiful architecture and peaceful environment. The monks were very welcoming.',
    created_at: new Date().toISOString(),
  },
];